### ISSUE TITLE
Requirements.txt and install instructions

### ISSUE THREAD

**Issue by Toddelismyname** [precice-forschungsprojekt/precice-generate#1]
**Short description**

**Details**

**Subtasks**
- [x] Add `requirements.txt`
- [x] Add a section `## How to install` to the `Readme.md`.
- [x] Add scripts to install automatically
- [x] pyproject.toml 
- [x] Fix errors and redundant stuff 

**Dependencies**
None
