### ISSUE TITLE
Implement version upgrade of precice-config generator

### ISSUE THREAD

**Issue by Toddelismyname** [precice-forschungsprojekt/precice-generate#7]
**Short description**
~~Idea is to use the precice-config generated by controller in v2 and then write code that takes the precicev2 in and ports it to precicev3~~
Things that need to be changed from controller code so we output v3 code
**Details**
Use this as help: [Porting Guide](https://precice.org/couple-your-code-porting-v2-3#precice-configuration-file)
**Subtasks**
- [x] #14
  - [x] 1. **Remove `<solver-interface>` tags**:
     - Delete lines containing `<solver-interface>` and `</solver-interface>`.
     - Move any attributes (e.g., `experimental`) from `<solver-interface>` to `<precice-configuration>`.
     - Move the `sync-mode` attribute to the new `<profiling>` tag.
  
  - [x]  2. **Update mesh dimensions configuration**:
     - Move `dimensions="2"` or `dimensions="3"` from `<solver-interface>` tag to each `<mesh>` tag, e.g., `<mesh name="MeshOne" dimensions="3">`.
- [x] #15
  - [x] 3. **Rename attributes**:
     - Rename `<m2n: ... />` attributes:
       - `from` -> `acceptor`
       - `to` -> `connector`
- [x] 4. **Add profiling mode**:
   - After the `<log>` tag, add `<profiling mode="all" />` if full profiling data is needed.

### Participants
- [x] #26
   - Replace `<use-mesh provide="true" ... />` with `<provide-mesh ... />`.
   - Replace `<use-mesh provide="false" ... />` with `<receive-mesh ... />`.

- [x] #28
   - Move `<read-data: ... waveform-order="1" />` to `<data:scalar/vector ... waveform-degree="1">`.

- [x] #12
   - Replace `<export:vtk />` with `<export:vtu />` or `<export:vtp />`.

- [x] #17
   - Replace `scaled-consistent` with `scaled-consistent-surface`.

- [x] #27
   - Remove `timing="initial/onadvance/ondemand"` attributes in the mapping configuration.

- [x] #19
    - Remove `preallocation="tree/compute/estimate/save/off"` attributes in the mapping configuration.

- [ ] 11. **Replace RBF related tags**:
    - Define RBF mappings in terms of the applied solver:
      - Options: `<mapping:rbf-global-direct ...`, `<mapping:rbf-global-iterative>`, `<mapping:rbf-pum-direct ...>`
    - Define the applied basis function as a subtag of the solver.
    - Use auto selection of an appropriate solver as follows:
      ```xml
      <mapping:rbf  ...>
        <basis-function:... />
      </mapping:rbf>
      ```

- [ ] 12. **Rename specific RBF configurations**:
    - Rename `<mapping:rbf... use-qr-decomposition="true" />` to:
      ```xml
      <mapping:rbf-global-direct ...>
        <basis-function:... />
      </mapping:rbf-global-direct>
      ```

### Data Actions
- [x] #20
    - Remove `regular-prior`, `regular-post`, `on-exchange-prior`, and `on-exchange-post`.

- [x] #21
    - Remove `read-mapping-prior`, `write-mapping-prior`, and `on-time-window-complete-post`.

- [x] #22
    - Remove `ComputeCurvatureAction` and `ScaleByDtAction` actions.

- [x] #23
    - Remove `vertexCallback` and `postAction` from `PythonAction` interface.

- [ ] 17. **Update PythonAction signature**:
    - Change `performAction` signature from `performAction(timewindowsize, time, data)` to `performAction(time, data)`.

### Coupling Schemes
- [x] 18. **Remove extrapolation order**:
    - Remove `<extraplation-order value="..." />` in `<coupling-scheme>`.

- [ ] 19. **Replace min iteration convergence measure**:
    - Replace `<min-iteration-convergence-measure min-iterations="3" ... />` with `<min-iterations value="3"/>`.

- [ ] 20. **Update Broyden acceleration**:
    - Remove plain Broyden acceleration.
    - Use IQN-IMVJ instead.

**Dependencies**
This task depends on all issues with subtask label  to be finished

**Comment by uekerman** [comment]
Such a script is extremely tedious to do since the preCICE configuration misuses xml namespaces, see https://github.com/precice/precice/issues/928.
I recommend porting the 8 examples manually instead.

**Comment by uekerman** [comment]
To make it even more complicated: The original 8 examples are still v1 I believe :/
